import { Fragment, type ReactNode } from 'react';
import { Link } from 'react-router';
import { useDocumentTitle } from '../layout/useDocumentTitle';
import source from '../../../../packages/react-tablekit/CHANGELOG.md?raw';

/**
 * `/changelog` (08 §1), rendered from the package's CHANGELOG.md.
 *
 * The file is generated by Changesets, so it uses a small and predictable subset of markdown:
 * `##` / `###` headings, `-` bullets with indented continuation lines, `**bold**` and `` `code` ``.
 * Rendering that subset directly keeps the site free of a markdown dependency for one page.
 */

/** Renders `**bold**` and `` `code` `` — the only inline markup in the generated file. */
function renderInline(text: string): ReactNode {
  return text.split(/(\*\*[^*]+\*\*|`[^`]+`)/g).map((part, index) => {
    const key = `${String(index)}-${part.slice(0, 12)}`;
    if (part.startsWith('**') && part.endsWith('**') && part.length > 4) {
      return <strong key={key}>{part.slice(2, -2)}</strong>;
    }
    if (part.startsWith('`') && part.endsWith('`') && part.length > 2) {
      return <code key={key}>{part.slice(1, -1)}</code>;
    }
    return <Fragment key={key}>{part}</Fragment>;
  });
}

function renderMarkdown(markdown: string): ReactNode[] {
  const blocks: ReactNode[] = [];
  let bullets: string[] = [];
  let paragraph: string[] = [];

  const flushBullets = () => {
    if (bullets.length === 0) return;
    const items = bullets;
    bullets = [];
    blocks.push(
      <ul key={`ul-${String(blocks.length)}`}>
        {items.map((item, index) => (
          <li key={`${String(index)}-${item.slice(0, 16)}`}>{renderInline(item)}</li>
        ))}
      </ul>,
    );
  };

  const flushParagraph = () => {
    if (paragraph.length === 0) return;
    const text = paragraph.join(' ');
    paragraph = [];
    blocks.push(<p key={`p-${String(blocks.length)}`}>{renderInline(text)}</p>);
  };

  for (const raw of markdown.split('\n')) {
    const line = raw.trim();

    if (line === '') {
      flushParagraph();
      flushBullets();
      continue;
    }
    // The file's own `# react-tablekit` title is dropped: the page supplies its own <h1>.
    if (line.startsWith('# ')) {
      flushParagraph();
      flushBullets();
      continue;
    }
    if (line.startsWith('### ')) {
      flushParagraph();
      flushBullets();
      blocks.push(<h3 key={`h3-${String(blocks.length)}`}>{line.slice(4)}</h3>);
      continue;
    }
    if (line.startsWith('## ')) {
      flushParagraph();
      flushBullets();
      const version = line.slice(3);
      blocks.push(
        <h2 key={`h2-${String(blocks.length)}`} id={`v${version}`}>
          {version}
        </h2>,
      );
      continue;
    }
    if (line.startsWith('- ')) {
      flushParagraph();
      bullets.push(line.slice(2));
      continue;
    }
    // An indented line continues the bullet above it.
    const last = bullets.length - 1;
    if (last >= 0) {
      bullets[last] = `${bullets[last] ?? ''} ${line}`;
      continue;
    }
    paragraph.push(line);
  }

  flushParagraph();
  flushBullets();
  return blocks;
}

export function ChangelogPage() {
  useDocumentTitle('Changelog');

  return (
    <article className="site-prose">
      <h1>Changelog</h1>
      <p className="site-lead">
        Every release, generated from the changesets in the repository. What counts as a breaking
        change is set out in the <Link to="/docs/versioning">versioning policy</Link>.
      </p>
      {renderMarkdown(source)}
    </article>
  );
}
