import type { TableSlots } from '../types';
import { ColumnActionsMenu, ColumnsMenu, FilterControl, FilterPanel } from './filters';
import {
  Ellipsis,
  FirstButton,
  LastButton,
  LoadMoreButton,
  NextButton,
  PageButton,
  PageSizeSelect,
  Pagination,
  PrevButton,
  RowRange,
} from './pagination';
import {
  Button,
  Checkbox,
  Chip,
  IconButton,
  Menu,
  MenuItem,
  Popover,
  Select,
  Spinner,
  TextInput,
  Tooltip,
} from './primitives';
import {
  EmptyState,
  ErrorBanner,
  ErrorState,
  LoadingOverlay,
  LoadingRow,
  SkeletonRows,
} from './states';
import {
  Body,
  Card,
  Cell,
  ColumnActionsButton,
  Container,
  DetailPanel,
  DetailRow,
  ExpandButton,
  FilterRow,
  FilterRowCell,
  Foot,
  FooterCell,
  FooterRow,
  GroupCell,
  GroupRow,
  Head,
  HeaderCell,
  HeaderRow,
  ResizeHandle,
  Root,
  Row,
  SortButton,
  SortIcon,
  Table,
  Toolbar,
} from './table';
import {
  ActiveFilterChips,
  ColumnsButton,
  DensityButton,
  ExportButton,
  FilterChip,
  FiltersButton,
  SearchInput,
  SelectionBar,
  SelectionCheckbox,
} from './toolbar';

/** The library's default implementation of every slot. */
export const defaultSlots = {
  Root,
  Toolbar,
  SearchInput,
  FiltersButton,
  FilterPanel,
  FilterControl,
  ActiveFilterChips,
  FilterChip,
  ColumnsButton,
  ColumnsMenu,
  DensityButton,
  ExportButton,
  SelectionBar,
  Container,
  Table,
  Head,
  HeaderRow,
  HeaderCell,
  SortButton,
  SortIcon,
  ColumnActionsButton,
  ColumnActionsMenu,
  ResizeHandle,
  FilterRow,
  FilterRowCell,
  Body,
  Row,
  Cell,
  SelectionCheckbox,
  ExpandButton,
  DetailRow,
  DetailPanel,
  GroupRow,
  GroupCell,
  Foot,
  FooterRow,
  FooterCell,
  LoadingRow,
  SkeletonRows,
  LoadingOverlay,
  Spinner,
  EmptyState,
  ErrorState,
  ErrorBanner,
  Pagination,
  PageButton,
  PrevButton,
  NextButton,
  FirstButton,
  LastButton,
  Ellipsis,
  PageSizeSelect,
  RowRange,
  LoadMoreButton,
  Card,
  Tooltip,
  Menu,
  MenuItem,
  Popover,
  Checkbox,
  Button,
  IconButton,
  Select,
  TextInput,
  Chip,
} satisfies TableSlots<unknown> as TableSlots<unknown>;

/** Every slot name, in documentation order. */
export const slotNames = Object.keys(defaultSlots) as (keyof TableSlots<unknown>)[];
